# Generated by Django 5.1.4 on 2025-01-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submane', '0002_payment_subscription_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'クレジット'), ('BANK', '銀行')], default='CREDIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', '月次'), ('YEARLY', '年次'), ('QUARTERLY', '四半期'), ('HALF-YEARLY', '半年')], default='MONTHLY', max_length=20),
        ),
    ]
