# Generated by Django 5.1.4 on 2025-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submane', '0003_alter_payment_type_alter_subscription_billing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', '月'), ('YEARLY', '年'), ('QUARTERLY', '3ヶ月'), ('HALF-YEARLY', '6ヶ月')], default='MONTHLY', max_length=20),
        ),
    ]
